import '../explore_page/widgets/gridarrowleft_item_widget.dart';import '../explore_page/widgets/griddressicon_item_widget.dart';import 'package:flutter/material.dart';import 'package:flutterqa/core/app_export.dart';import 'package:flutterqa/widgets/app_bar/appbar_image.dart';import 'package:flutterqa/widgets/app_bar/appbar_searchview.dart';import 'package:flutterqa/widgets/app_bar/custom_app_bar.dart';
// ignore_for_file: must_be_immutable
class ExplorePage extends StatelessWidget {ExplorePage({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), appBar: CustomAppBar(height: getVerticalSize(67), title: AppbarSearchview(margin: getMargin(left: 16), hintText: "Search Product", controller: searchController), actions: [AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgDownload, margin: getMargin(left: 16, top: 16, right: 16)), Container(height: getSize(24), width: getSize(24), margin: getMargin(left: 16, top: 16, right: 32), child: Stack(alignment: Alignment.topRight, children: [AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgNotificationicon, onTap: () {onTapNotificationico1(context);}), AppbarImage(height: getSize(8), width: getSize(8), svgPath: ImageConstant.imgClosePink300, margin: getMargin(left: 14, right: 2, bottom: 16))]))]), body: Container(width: double.maxFinite, padding: getPadding(left: 16, top: 25, right: 16, bottom: 25), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("Man Fashion", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleSmallPoppinsPrimaryContainer.copyWith(letterSpacing: getHorizontalSize(0.5))), Expanded(child: Padding(padding: getPadding(top: 13), child: GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: getVerticalSize(93), crossAxisCount: 4, mainAxisSpacing: getHorizontalSize(21), crossAxisSpacing: getHorizontalSize(21)), physics: NeverScrollableScrollPhysics(), itemCount: 6, itemBuilder: (context, index) {return GridarrowleftItemWidget();}))), Padding(padding: getPadding(top: 23), child: Text("Woman Fashion", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleSmallPoppinsPrimaryContainer.copyWith(letterSpacing: getHorizontalSize(0.5)))), Padding(padding: getPadding(top: 13), child: GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: getVerticalSize(94), crossAxisCount: 4, mainAxisSpacing: getHorizontalSize(21), crossAxisSpacing: getHorizontalSize(21)), physics: NeverScrollableScrollPhysics(), itemCount: 7, itemBuilder: (context, index) {return GriddressiconItemWidget();}))])))); } 
/// Navigates to the notificationScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [Navigator] widget
/// to push the named route for the notificationScreen.
onTapNotificationico1(BuildContext context) { Navigator.pushNamed(context, AppRoutes.notificationScreen); } 
 }
