import 'package:flutter/material.dart';import 'package:flutter_rating_bar/flutter_rating_bar.dart';import 'package:flutterqa/core/app_export.dart';import 'package:flutterqa/widgets/app_bar/appbar_image.dart';import 'package:flutterqa/widgets/app_bar/appbar_subtitle_1.dart';import 'package:flutterqa/widgets/app_bar/custom_app_bar.dart';import 'package:flutterqa/widgets/custom_elevated_button.dart';import 'package:flutterqa/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class WriteReviewFillScreen extends StatelessWidget {WriteReviewFillScreen({Key? key}) : super(key: key);

TextEditingController addreviewController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: getVerticalSize(56), leadingWidth: 40, leading: AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgArrowleftBlueGray300, margin: getMargin(left: 16, top: 16, bottom: 15), onTap: () {onTapArrowleft3(context);}), title: AppbarSubtitle1(text: "Write Review", margin: getMargin(left: 12))), body: Container(width: double.maxFinite, padding: getPadding(left: 15, top: 27, right: 15, bottom: 27), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [SizedBox(width: getHorizontalSize(343), child: Text("Please write Overall level of satisfaction with your shipping / Delivery Service", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleSmallPoppinsPrimaryContainer.copyWith(letterSpacing: getHorizontalSize(0.5)))), Padding(padding: getPadding(top: 13), child: RatingBar.builder(initialRating: 0, minRating: 0, direction: Axis.horizontal, allowHalfRating: false, itemSize: getVerticalSize(32), unratedColor: appTheme.blue50, itemCount: 1, updateOnDrag: true, onRatingUpdate: (rating) {}, itemBuilder: (context, _) {return Icon(Icons.star, color: appTheme.yellow700);})), Padding(padding: getPadding(top: 22), child: Text("Write Your Review", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleSmallPoppinsPrimaryContainer.copyWith(letterSpacing: getHorizontalSize(0.5)))), CustomTextFormField(controller: addreviewController, margin: getMargin(top: 13, bottom: 5), contentPadding: getPadding(left: 16, top: 17, right: 16, bottom: 17), textStyle: CustomTextStyles.labelLargeBluegray300, hintText: "Add Review", hintStyle: CustomTextStyles.labelLargeBluegray300, maxLines: 8, filled: true, fillColor: theme.colorScheme.onPrimaryContainer.withOpacity(1))])), bottomNavigationBar: CustomElevatedButton(text: "Write Review", margin: getMargin(left: 16, right: 16, bottom: 34), buttonStyle: CustomButtonStyles.outlinePrimaryTL5.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(57)))), buttonTextStyle: CustomTextStyles.titleSmallPoppinsOnPrimaryContainer))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleft3(BuildContext context) { Navigator.pop(context); } 
 }
