import 'package:flutter/material.dart';import 'package:flutter_rating_bar/flutter_rating_bar.dart';import 'package:flutterqa/core/app_export.dart';import 'package:flutterqa/widgets/app_bar/appbar_image.dart';import 'package:flutterqa/widgets/app_bar/appbar_subtitle_1.dart';import 'package:flutterqa/widgets/app_bar/custom_app_bar.dart';import 'package:flutterqa/widgets/custom_elevated_button.dart';class ReviewProductScreen extends StatelessWidget {const ReviewProductScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), appBar: CustomAppBar(height: getVerticalSize(56), leadingWidth: 43, leading: AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgArrowleftBlueGray300, margin: getMargin(left: 19, top: 16, bottom: 15), onTap: () {onTapArrowleft4(context);}), title: AppbarSubtitle1(text: "5 Review", margin: getMargin(left: 12))), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: getPadding(top: 18), child: Padding(padding: getPadding(left: 19, right: 23, bottom: 5), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgProfilepicture, height: getSize(48), width: getSize(48), radius: BorderRadius.circular(getHorizontalSize(24))), Padding(padding: getPadding(left: 16, top: 2, bottom: 4), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("James Lawson", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleSmallPoppinsPrimaryContainer.copyWith(letterSpacing: getHorizontalSize(0.5))), Padding(padding: getPadding(top: 4), child: RatingBar.builder(initialRating: 0, minRating: 0, direction: Axis.horizontal, allowHalfRating: false, itemSize: getVerticalSize(16), itemCount: 1, updateOnDrag: true, onRatingUpdate: (rating) {}, itemBuilder: (context, _) {return Icon(Icons.star);}))]))]), Container(width: getHorizontalSize(333), margin: getMargin(top: 18), child: Text("air max are always very comfortable fit, clean and just perfect in every way. just the box was too small and scrunched the sneakers up a little bit, not sure if the box was always this small but the 90s are and will always be one of my favorites.", maxLines: 5, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.bodySmallPoppinsBluegray30012.copyWith(letterSpacing: getHorizontalSize(0.5)))), Padding(padding: getPadding(top: 16), child: Text("December 10, 2016", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.bodySmallPoppinsBluegray30010.copyWith(letterSpacing: getHorizontalSize(0.5))))])))), bottomNavigationBar: CustomElevatedButton(text: "Write Review", margin: getMargin(left: 19, right: 13, bottom: 58), buttonStyle: CustomButtonStyles.outlinePrimaryTL5.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(57)))), buttonTextStyle: CustomTextStyles.titleSmallPoppinsOnPrimaryContainer, onTap: () {onTapWritereview(context);}))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleft4(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the writeReviewFillScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [Navigator] widget
/// to push the named route for the writeReviewFillScreen.
onTapWritereview(BuildContext context) { Navigator.pushNamed(context, AppRoutes.writeReviewFillScreen); } 
 }
