import 'package:flutter/material.dart';import 'package:flutterqa/core/app_export.dart';import 'package:flutterqa/widgets/app_bar/appbar_image.dart';import 'package:flutterqa/widgets/app_bar/appbar_subtitle.dart';import 'package:flutterqa/widgets/app_bar/custom_app_bar.dart';import 'package:flutterqa/widgets/custom_elevated_button.dart';import 'package:flutterqa/widgets/custom_outlined_button.dart';class VisualSearchScreen extends StatelessWidget {const VisualSearchScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), body: SizedBox(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(padding: getPadding(top: 8, bottom: 8), decoration: AppDecoration.outline, child: CustomAppBar(height: getVerticalSize(28), leadingWidth: 32, leading: AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgArrowleftOnprimary, margin: getMargin(left: 8), onTap: () {onTapArrowleft25(context);}), centerTitle: true, title: AppbarSubtitle(text: "Visual search"))), SizedBox(height: getVerticalSize(724), width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgImage724x375, height: getVerticalSize(724), width: getHorizontalSize(375), alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Padding(padding: getPadding(left: 16, top: 197, right: 16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(325), margin: getMargin(right: 17), child: Text("Search for an outfit by taking a photo or uploading an image", maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineSmallMetropolis)), CustomElevatedButton(text: "TAKE A PHOTO", margin: getMargin(top: 26), buttonStyle: CustomButtonStyles.outlineRed8003f.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(48)))), buttonTextStyle: CustomTextStyles.titleSmallOnPrimaryContainer), CustomOutlinedButton(text: "UPLOAD AN IMAGE", margin: getMargin(top: 16), buttonStyle: CustomButtonStyles.outlineOnPrimaryContainer.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(48)))), buttonTextStyle: CustomTextStyles.titleSmallOnPrimaryContainer)])))]))])))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleft25(BuildContext context) { Navigator.pop(context); } 
 }
