import 'package:flutter/material.dart';import 'package:flutterqa/core/app_export.dart';import 'package:flutterqa/presentation/cart_page/cart_page.dart';import 'package:flutterqa/presentation/catalog_one_page/catalog_one_page.dart';import 'package:flutterqa/presentation/dashboard_container_page/dashboard_container_page.dart';import 'package:flutterqa/presentation/explore_page/explore_page.dart';import 'package:flutterqa/presentation/my_profile_my_orders_order_details_page/my_profile_my_orders_order_details_page.dart';import 'package:flutterqa/presentation/offer_screen_page/offer_screen_page.dart';import 'package:flutterqa/widgets/app_bar/appbar_image.dart';import 'package:flutterqa/widgets/app_bar/custom_app_bar.dart';import 'package:flutterqa/widgets/custom_bottom_bar.dart';import 'package:flutterqa/widgets/custom_floating_button.dart';class CatalogOneTabContainerScreen extends StatefulWidget {const CatalogOneTabContainerScreen({Key? key}) : super(key: key);

@override CatalogOneTabContainerScreenState createState() =>  CatalogOneTabContainerScreenState();
 }

// ignore_for_file: must_be_immutable
class CatalogOneTabContainerScreenState extends State<CatalogOneTabContainerScreen> with  TickerProviderStateMixin {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray50, body: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(367), margin: getMargin(left: 8, top: 8), decoration: AppDecoration.outline1, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [CustomAppBar(height: getVerticalSize(88), title: Padding(padding: getPadding(left: 8), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgArrowleftOnprimary, margin: getMargin(right: 223), onTap: () {onTapArrowleft30(context);}), Align(alignment: Alignment.centerLeft, child: Padding(padding: getPadding(left: 6, top: 31), child: Text("Women’s tops", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.displaySmall)))])), actions: [AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgBaselinesearch24pxGray900, margin: getMargin(left: 11, right: 11, bottom: 64))]), Padding(padding: getPadding(left: 8, top: 12), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: getVerticalSize(30), width: getHorizontalSize(315), child: TabBar(controller: tabviewController, tabs: [Tab(child: Text("T-shirts", overflow: TextOverflow.ellipsis)), Tab(child: Text("Crop tops", overflow: TextOverflow.ellipsis)), Tab(child: Text("Sleeveless", overflow: TextOverflow.ellipsis))])), Container(width: getHorizontalSize(100), margin: getMargin(left: 8), padding: getPadding(left: 30, top: 7, right: 30, bottom: 7), decoration: AppDecoration.txtFill2.copyWith(borderRadius: BorderRadiusStyle.txtCircleBorder15), child: Text("Shirts", overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallOnPrimaryContainer))]))])), SizedBox(height: getVerticalSize(630), child: TabBarView(controller: tabviewController, children: [CatalogOnePage(), CatalogOnePage(), CatalogOnePage()]))])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}), floatingActionButton: CustomFloatingButton(height: 36, width: 36, backgroundColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), decoration: FloatingButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(svgPath: ImageConstant.imgIcon, height: getVerticalSize(18.0), width: getHorizontalSize(18.0))))); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.dashboardContainerPage; case BottomBarEnum.Explore: return AppRoutes.explorePage; case BottomBarEnum.Cart: return AppRoutes.cartPage; case BottomBarEnum.Offer: return AppRoutes.offerScreenPage; case BottomBarEnum.Account: return AppRoutes.myProfileMyOrdersOrderDetailsPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.dashboardContainerPage: return DashboardContainerPage(); case AppRoutes.explorePage: return ExplorePage(); case AppRoutes.cartPage: return CartPage(); case AppRoutes.offerScreenPage: return OfferScreenPage(); case AppRoutes.myProfileMyOrdersOrderDetailsPage: return MyProfileMyOrdersOrderDetailsPage(); default: return DefaultWidget();} } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleft30(BuildContext context) { Navigator.pop(context); } 
 }
